apiVersion: v1
kind: Service
metadata:
  name: sip-app
  namespace: sip-system
  labels:
    app.kubernetes.io/name: sip-app
    app.kubernetes.io/component: signaling
    app.kubernetes.io/part-of: micronaut-sip
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: sip-app
  ports:
    - name: sip-udp
      port: 5060
      targetPort: 5060
      protocol: UDP
    - name: sip-tcp
      port: 5060
      targetPort: 5060
      protocol: TCP
    - name: http-mgmt
      port: 8080
      targetPort: 8080
      protocol: TCP
