apiVersion: v1
kind: Service
metadata:
  name: sip-app
  namespace: sip-system
  labels:
    app.kubernetes.io/name: sip-app
    app.kubernetes.io/component: signaling
    app.kubernetes.io/part-of: micronaut-sip
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: sip-app
  ports:
    - name: sip-udp
      port: 5060
      targetPort: 5060
      protocol: UDP
    - name: sip-tcp
      port: 5060
      targetPort: 5060
      protocol: TCP
    - name: http-mgmt
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: rtp-10000
      port: 10000
      targetPort: 10000
      protocol: UDP
    - name: rtp-10002
      port: 10002
      targetPort: 10002
      protocol: UDP
    - name: rtp-10004
      port: 10004
      targetPort: 10004
      protocol: UDP
    - name: rtp-10006
      port: 10006
      targetPort: 10006
      protocol: UDP
    - name: rtp-10008
      port: 10008
      targetPort: 10008
      protocol: UDP
    - name: rtp-10010
      port: 10010
      targetPort: 10010
      protocol: UDP
