micronaut.application.name=sip-app
sip.server.udp-enabled=true
sip.server.udp.host=0.0.0.0
sip.server.udp.port=5060
sip.server.tcp-enabled=true
sip.server.tcp.host=0.0.0.0
sip.server.tcp.port=5060
sip.server.enabled=true
sip.server.server-name=Micronaut-SIP/1.0
sip.server.request-timeout-ms=5000

# RFC 4240 NetAnn Configuration
netann.call.max-active-announcements=2000
netann.call.max-announcements-per-ip=2000

# Mailbox & Object Storage Configuration
micronaut.object-storage.local.default.enabled=true
micronaut.object-storage.local.default.path=build/storage/mailbox
mailbox.enabled=true
mailbox.user=mailbox
mailbox.max-recording-seconds=30
mailbox.finish-dtmf=#
