micronaut.application.name=sip-app
sip.server.udp-enabled=true
sip.server.udp.host=0.0.0.0
sip.server.udp.port=5060
sip.server.tcp-enabled=true
sip.server.tcp.host=0.0.0.0
sip.server.tcp.port=5060
sip.server.enabled=true
sip.server.server-name=Micronaut-SIP/1.0
sip.server.request-timeout-ms=5000
