apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sip-system

resources:
  - namespace.yaml
  - sip-app/configmap.yaml
  - sip-app/deployment.yaml
  - sip-app/service.yaml
  - micronaut-netann/configmap.yaml
  - micronaut-netann/deployment.yaml
  - micronaut-netann/service.yaml

commonLabels:
  app.kubernetes.io/part-of: micronaut-sip
