plugins {
    id("io.micronaut.application") version "5.0.2"
    id("com.gradleup.shadow") version "9.4.1"
}

version = "0.1." + (findProperty("buildNumber") ?: "3")
group = "net.pilgrim"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")

    implementation(project(":micronaut-sdp"))
    implementation(project(":micronaut-rtp"))
    implementation(project(":micronaut-sip"))
    implementation("io.projectreactor:reactor-core")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut:micronaut-management")

    runtimeOnly("ch.qos.logback:logback-classic")

    testImplementation(project(":micronaut-sdp"))
    testImplementation(project(":micronaut-rtp"))
    testImplementation(project(":micronaut-sip"))
    testImplementation("io.projectreactor:reactor-test")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
    mainClass = "net.pilgrim.netann.NetannApplication"
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("net.pilgrim.*")
    }
}

tasks.withType(AbstractTestTask).configureEach {
    failOnNoDiscoveredTests = false
}

graalvmNative {
    binaries {
        main {
            imageName = "micronaut-netann"
            mainClass = "net.pilgrim.netann.NetannApplication"
            buildArgs.addAll(
                "--no-fallback",
                "-H:+ReportExceptionStackTraces",
                "-H:IncludeResources=prompts/.*"
            )
        }
    }
}
