micronaut.application.name=micronaut-netann
sip.server.udp-enabled=true
sip.server.udp.host=0.0.0.0
sip.server.udp.port=5060
sip.server.tcp-enabled=true
sip.server.tcp.host=0.0.0.0
sip.server.tcp.port=5060
sip.server.enabled=true
sip.server.server-name=Micronaut-NetAnn/1.0
sip.server.request-timeout-ms=5000
netann.call.max-active-announcements=2000
netann.call.max-announcements-per-ip=2000
